name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  greet:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Hello! My name is ${{ secrets.USER_EMAIL }}."
          echo "My password is ${{ secrets.USER_PASSWORD }}."

  lint:
    name: Lint (flake8)
    runs-on: ubuntu-latest
    needs: greet
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 .

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Check package versions
        run: pip index versions scikit-learn
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run unit tests
        run: pytest tests/unit --maxfail=1 --disable-warnings -q

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit_tests
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_RUN_ID:       ${{ secrets.MLFLOW_RUN_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install MLflow client
        run: pip install mlflow
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run integration tests
        run: pytest tests/integration --maxfail=1 --disable-warnings -q
